[tool.briefcase]
project_name = "pancake"
bundle = "afreto.top"
version = "0.0.1"
url = "https://pancake.afreto.top"
license = "MIT license"
author = 'afreto'
author_email = "kongandmarx@163.com"

[tool.briefcase.app.pancake]
formal_name = "pancake"
description = "My first application"
icon = "src/pancake/resources/pancake"
sources = ['src/pancake']
requires = [
]


[tool.briefcase.app.pancake.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.pancake.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.pancake.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.pancake.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.pancake.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
