version: "3"
services:
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - CONTEXT_PATH=bwg.afreto.top
    volumes:
      - /etc/airsonic:/config
      - /data/airsonic/music:/music
      - /data/airsonic/playlists:/playlists
      - /data/airsonic/podcasts:/podcasts
      - /data/airsonic/media:/media #optional
    ports:
      - 10020:4040
    restart: unless-stopped